makeCacheMatrix<-function(x=matrix()){
inv<-NULLset<-function(y){
  x<<-y
  inv<<-NULL
  }
  get<-function()x
  setInverse<-function(inverse)inv<<-inverse
  getInverse<-function()inv
  list(set=set,
       get=get,
       setInverse=setInverse,
       getInverse=getInverse)
}